name: CI/CD Pipeline for Quiz App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aryaanil8319@gmail.com
          password: Arya.Anil@8319

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy Application
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest
          docker stop quiz-app || true
          docker rm quiz-app || true
          docker run -d -p 3000:3000 --name quiz-app ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest
